Dz1
ElizavetaMikhina/2024-2-VK-EDU-Frontend-E-Mikhina pull request #1
Opened 2024-09-20 19:00 UTC by ElizavetaMikhina

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Написано тело функций для convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
* Написаны тесты для convertBytesToHuman.js в файле convertBytesToHuman.test.js

2024-09-22 08:02 UTC, RomanBarannickov requested changes

2024-09-22 08:02 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(NaN)).toBe(false);
а для объекта, массива, функции?)

2024-09-22 08:02 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +  const humanReadableSize = (bytes / Math.pow(1024, sizeIndex));
Интересное решение
объясни логику работы данных строк

2024-09-22 08:58 UTC, ElizavetaMikhina commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(NaN)).toBe(false);
поняла, сделаю)

2024-09-22 09:33 UTC, ElizavetaMikhina commented on convertBytesToHuman.js
> +  const humanReadableSize = (bytes / Math.pow(1024, sizeIndex));
Здесь я использовала логарифм по основанию 1024 для того, чтобы найти степень, в которую нужно возвести число 1024, чтобы получить размер файла в байтах.
Math.log(bytes) / Math.log(1024) - вычисляю, сколько раз нужно разделить число на 1024, чтобы перевести его в нужную единицу измерения (кб, мб и т.д.)
Math.floor - округляю число в меньшую сторону до ближайшего целого, чтобы оно соответствовало индексам массива const sizes = ['B', 'KB', 'MB', 'GB', 'TB'], таким образом выбираю нужную единицу измерения.

строка 2: const humanReadableSize = (bytes / Math.pow(1024, sizeIndex)); - делю  переданное значение bytes на значение 1024 в нужной степени, чтобы получить размер файла в нужных единицах измерения.

2024-09-22 09:45 UTC, ElizavetaMikhina commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(NaN)).toBe(false);
готово!)

2024-09-23 08:05 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin approve

2024-09-23 08:07 UTC, kgrechin approved these changes

2024-09-23 14:00 UTC, martinkomitsky approved these changes
12!

2024-09-23 14:01 UTC, merged